---
version: '2'

services:
  postgres_ods:
    container_name: database_ods
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/data/postgres_ods"
    volumes:
       - postgres_ods:/data/postgres_ods
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "15432:5432"
    restart: unless-stopped

volumes:
    postgres_ods:
